# Generated by Django 5.2.5 on 2025-09-10 22:28

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_alter_onboard_problems_alter_onboard_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_index_content',
            field=models.TextField(blank=True, help_text='Supports markdown', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='footer_note',
            field=models.TextField(blank=True, default='published with [BōcPress](https://bocpress.co.uk/).', help_text='Supports markdown', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='redirect_domain',
            field=models.CharField(blank=True, help_text='Retiring your BōcPress blog? We can redirect to your new domain.', max_length=150, null=True, validators=[main.validators.validate_domain_name]),
        ),
    ]
