# Generated by Django 5.2.5 on 2025-09-11 20:18

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_user_blog_index_content_alter_user_footer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_posts_in_nav',
            field=models.BooleanField(default=False, help_text='Show/hide posts in the navigation bar.', verbose_name='Show Posts In Nav'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_posts_on_homepage',
            field=models.BooleanField(default=False, help_text='Show/hide posts on the homepage.', verbose_name='Show Posts On Homepage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_domain',
            field=models.CharField(blank=True, help_text="To setup: Add an A record in your domain's DNS with IP 78.47.67.77", max_length=150, null=True, validators=[main.validators.validate_domain_name]),
        ),
    ]
