# Generated by Django 5.2.5 on 2025-09-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_user_show_posts_in_nav_user_show_posts_on_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_posts_on_homepage',
            field=models.BooleanField(default=True, help_text='Show/hide posts on the homepage.', verbose_name='Show Posts On Homepage'),
        ),
    ]
