# Generated by Django 5.2.5 on 2025-09-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_alter_user_show_posts_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noindex_on',
            field=models.BooleanField(default=False, help_text='Add a noindex meta tag so your blog is not indexed by search engines.', verbose_name='noindex: Prevent Search Engine Indexing'),
        ),
    ]
