# Generated by Django 5.2.5 on 2025-09-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_user_noindex_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_page_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
