# Generated by Django 5.2.5 on 2025-09-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_user_posts_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nDisallow:\nAllow: /', help_text='Custom robots.txt content for this user. Leave blank for default.', null=True, verbose_name='robots.txt'),
        ),
    ]
